# Generated by Django 5.1.1 on 2024-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rubric_alter_product_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/None/', verbose_name='Изображение'),
        ),
    ]
