# Generated by Django 5.1.1 on 2024-09-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rubrics',
            field=models.ManyToManyField(related_name='products', to='store.rubric', verbose_name='Рубрики'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='image',
            field=models.ImageField(blank=True, upload_to='rubrics/', verbose_name='Изображение'),
        ),
    ]
