# Generated by Django 5.1.1 on 2024-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_slug_alter_rubric_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
