# Generated by Django 5.1.1 on 2024-10-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_sale_information_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('title',), 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
    ]
