# Generated by Django 5.1.1 on 2024-10-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_brand_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discont',
            field=models.PositiveIntegerField(choices=[(0, 'без скидки'), (5, '5% скидка'), (10, '10% скидка'), (15, '15% скидка'), (20, '20% скидка'), (25, '25% скидка'), (30, '30% скидка'), (35, '35% скидка'), (40, '40% скидка'), (45, '45% скидка'), (50, '50% скидка'), (55, '55% скидка'), (60, '60% скидка'), (65, '65% скидка'), (70, '70% скидка')], default=0, verbose_name='Скидка'),
        ),
    ]
