# Generated by Django 5.1.3 on 2024-11-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_additional_information_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('0', 'в продаже'), ('1', 'нет в наличии')], default=('0', 'в продаже'), max_length=50),
        ),
    ]
