version: "3.9"

services:

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  webapp:
    restart: unless-stopped
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
    depends_on:
        - redis
    volumes:
      - ./mine_shop:/app/mine_shop
    command: [ "python3", "./mine_shop/manage.py", "runserver", "0.0.0.0:8000" ]
