# Generated by Django 5.1.1 on 2024-10-28 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес доставки')),
                ('city', models.CharField(max_length=50, verbose_name='Населенный пункт')),
                ('postcode', models.IntegerField(blank=True, null=True, verbose_name='Почтовый код')),
                ('email', models.EmailField(blank=True, error_messages={'max_length': 'Атрибут не может состоять более чем из 70 символов', 'min_length': 'Атрибут не может состоять менее чем из 3 символов'}, max_length=70, verbose_name='Адрес эл.почты')),
                ('phonenumber', models.CharField(max_length=70, error_messages={'invalid': 'Неверный телефонный номер'}, verbose_name='Телефонный номер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Обязательное условие'}, max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, default='', error_messages={'max_length': 'Атрибут не может состоять более чем из 50 символов'}, max_length=50, verbose_name='Фамилия')),
                ('company_name', models.CharField(blank=True, default='', error_messages={'max_length': 'Атрибут не может состоять более чем из 50 символов', 'min_length': 'Атрибут не может состоять менее чем из 3 символов'}, max_length=100, verbose_name='Компания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Персона',
            },
        ),
    ]
