# Generated by Django 5.1.2 on 2024-11-05 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=70, error_messages={'invalid': 'Неверный телефонный номер'}, verbose_name='Телефонный номер')),
                ('order_content', models.CharField(max_length=2000, error_messages={'invalid': 'Ошибка в заказе'}, verbose_name='Данные заказа')),
                ('person_content', models.CharField(max_length=200, error_messages={'invalid': 'Ошибка в данных'}, verbose_name='Данные пользователя')),
                ('address_content', models.CharField(max_length=200, error_messages={'invalid': 'Ошибка в данных'}, verbose_name='Данные адреса доставки')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('move_to', models.PositiveIntegerField(choices=[(0, 'Пункт выдачи'), (1, 'Адрес заказчика')], default=0, verbose_name='Доставить на')),
                ('payment_conditions', models.PositiveIntegerField(choices=[(0, 'Ожидает оплаты'), (1, 'Оплачен'), (2, 'Оплачивается при вручении б/н'), (3, 'Оплачивается при вручении нал.д/с')], default=0, verbose_name='Статус оплаты')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Заказан'), (1, 'Доставлен')], default=0, verbose_name='Статус заказа')),
                ('time_placed', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('time_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
