# Generated by Django 5.1.2 on 2024-11-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-time_placed',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_conditions',
            field=models.PositiveIntegerField(choices=[(0, 'Ожидает оплаты'), (1, 'Оплачен'), (2, 'При вручении, б/н'), (3, 'При вручении, нал.д/с')], default=0, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Заказан'), (1, 'Доставлен'), (2, 'Отменен')], default=0, verbose_name='Статус заказа'),
        ),
    ]
