# Generated by Django 5.1.1 on 2024-10-13 10:55

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательное. Не более 75 символов. Допустимы буквы, цифры и символы @/./+/-/_', max_length=75, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='имя пользователя'),
        ),
    ]
