# Generated by Django 5.1.1 on 2024-10-23 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_brand_options'),
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTools',
            fields=[
                ('max_length_c', models.SmallIntegerField(auto_created=True, default=4, editable=False, verbose_name="Максимальное число записей в категории 'Сравнение'")),
                ('max_length_w', models.SmallIntegerField(auto_created=True, default=20, editable=False, verbose_name="Максимальное число записей в категории 'Избранное'")),
                ('max_length_rv', models.SmallIntegerField(auto_created=True, default=8, editable=False, verbose_name="Максимальное число записей в категории 'Недавно просмотренное'")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recently_viewed', serialize=False, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Инструменты авторизованного пользователя',
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True, verbose_name='Просмотрено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Идентификатор продукта')),
                ('recently_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rv_items', to='users.usertools')),
            ],
            options={
                'verbose_name': 'Недавно просмотренный товар',
                'ordering': ('-added',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True, verbose_name='Добавлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Идентификатор продукта')),
                ('recently_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_items', to='users.usertools')),
            ],
            options={
                'verbose_name': 'Товар к сравнению',
                'ordering': ('-added',),
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True, verbose_name='Добавлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Идентификатор продукта')),
                ('recently_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_items', to='users.usertools')),
            ],
            options={
                'verbose_name': 'Избранный товар',
                'ordering': ('-added',),
            },
        ),
    ]
